/**
 * Shopify Session Token Verification Middleware
 *
 * Verifies JWT tokens generated by Shopify App Bridge.
 * Tokens are only valid when the app is embedded in the Shopify admin.
 *
 * Token payload contains:
 * - iss: shop domain (e.g., "https://store.myshopify.com")
 * - dest: shop URL (e.g., "https://store.myshopify.com/admin")
 * - aud: Shopify API key (the app's API key)
 * - sub: user ID
 * - exp: expiration time (Unix timestamp)
 * - nbf: not before time
 * - iat: issued at time
 */

import jwt from 'jsonwebtoken';

const SHOPIFY_API_SECRET = process.env.SHOPIFY_API_SECRET;
const SHOPIFY_API_KEY = process.env.SHOPIFY_API_KEY;

/**
 * Middleware to verify Shopify session tokens
 * Extracts shop domain from the JWT and attaches to req object
 * Falls back gracefully if no token is present (for standalone mode)
 */
export function verifySessionToken(req, res, next) {
  const authHeader = req.headers.authorization;

  // If Authorization header with Bearer token is present, verify it
  if (authHeader && authHeader.startsWith('Bearer ')) {
    const token = authHeader.slice(7); // Remove "Bearer " prefix

    try {
      // Verify JWT using Shopify API secret as signing key
      const decoded = jwt.verify(token, SHOPIFY_API_SECRET, {
        algorithms: ['HS256'],
      });

      // Validate audience matches the API key
      if (decoded.aud !== SHOPIFY_API_KEY) {
        console.warn('[SessionToken] Invalid token audience:', decoded.aud);
        return res.status(401).json({
          error: 'Invalid token audience',
          code: 'INVALID_AUDIENCE',
        });
      }

      // Validate token is not expired
      if (decoded.exp && decoded.exp < Math.floor(Date.now() / 1000)) {
        console.warn('[SessionToken] Token expired');
        return res.status(401).json({
          error: 'Token expired',
          code: 'TOKEN_EXPIRED',
        });
      }

      // Extract shop domain from dest (e.g., "https://store.myshopify.com/admin" -> "store.myshopify.com")
      try {
        const destUrl = new URL(decoded.dest);
        req.shopDomain = destUrl.hostname;
        req.sessionTokenPayload = decoded;
        req.authMethod = 'session_token'; // Track which auth method was used

        console.debug('[SessionToken] Verified for shop:', req.shopDomain);
        return next();
      } catch (err) {
        console.warn('[SessionToken] Failed to extract shop domain from dest:', err.message);
        return res.status(401).json({
          error: 'Invalid token format',
          code: 'INVALID_TOKEN_FORMAT',
        });
      }
    } catch (err) {
      // Token verification failed — log and fall through to header-based auth
      console.warn('[SessionToken] Verification failed:', err.message);
      // Don't return error here — fall through to check X-Shop-Domain header
    }
  }

  // No valid session token — proceed to next auth method (X-Shop-Domain header)
  next();
}

export default verifySessionToken;
