/**
 * Shopify Session Token Verification Middleware
 *
 * Verifies JWT tokens generated by Shopify App Bridge.
 * Tokens are only valid when the app is embedded in the Shopify admin.
 *
 * Token payload contains:
 * - iss: shop domain (e.g., "https://store.myshopify.com")
 * - dest: shop URL (e.g., "https://store.myshopify.com/admin")
 * - aud: Shopify API key (the app's API key)
 * - sub: user ID
 * - exp: expiration time (Unix timestamp)
 * - nbf: not before time
 * - iat: issued at time
 */

import jwt from 'jsonwebtoken';
import { getUserShopDomain, getShop } from '../db/database.js';

const SHOPIFY_API_SECRET = process.env.SHOPIFY_API_SECRET;
const SHOPIFY_API_KEY = process.env.SHOPIFY_API_KEY;

/**
 * Middleware to verify Shopify session tokens
 * Extracts shop domain from the JWT and attaches to req object
 * Falls back gracefully if no token is present (for standalone mode)
 */
export function verifySessionToken(req, res, next) {
  const authHeader = req.headers.authorization;

  // Also accept token from query parameter (for OAuth redirect flows where headers can't be sent)
  const queryToken = req.query?.token;

  // If Authorization header with Bearer token is present, verify it
  const bearerToken = (authHeader && authHeader.startsWith('Bearer ')) ? authHeader.slice(7) : queryToken;
  if (bearerToken) {
    const token = bearerToken;

    try {
      // Verify JWT using Shopify API secret as signing key
      const decoded = jwt.verify(token, SHOPIFY_API_SECRET, {
        algorithms: ['HS256'],
      });

      // Validate audience matches the API key
      if (decoded.aud !== SHOPIFY_API_KEY) {
        console.warn('[SessionToken] Invalid token audience:', decoded.aud);
        return res.status(401).json({
          error: 'Invalid token audience',
          code: 'INVALID_AUDIENCE',
        });
      }

      // Validate token is not expired
      if (decoded.exp && decoded.exp < Math.floor(Date.now() / 1000)) {
        console.warn('[SessionToken] Token expired');
        return res.status(401).json({
          error: 'Token expired',
          code: 'TOKEN_EXPIRED',
        });
      }

      // Extract shop domain from dest (e.g., "https://store.myshopify.com/admin" -> "store.myshopify.com")
      try {
        const destUrl = new URL(decoded.dest);
        req.shopDomain = destUrl.hostname;
        req.sessionTokenPayload = decoded;
        req.authMethod = 'session_token'; // Track which auth method was used

        console.debug('[SessionToken] Verified for shop:', req.shopDomain);
        return next();
      } catch (err) {
        console.warn('[SessionToken] Failed to extract shop domain from dest:', err.message);
        return res.status(401).json({
          error: 'Invalid token format',
          code: 'INVALID_TOKEN_FORMAT',
        });
      }
    } catch (err) {
      // Shopify token verification failed — try our own JWT (signed with JWT_SECRET)
      try {
        const decoded = jwt.verify(token, process.env.JWT_SECRET, { algorithms: ['HS256'] });
        let shopDomain = decoded.shopDomain;

        // If JWT has userId but no shopDomain, look up linked shop from DB
        if (!shopDomain && decoded.userId) {
          shopDomain = getUserShopDomain(decoded.userId);
        }

        if (shopDomain) {
          req.shopDomain = shopDomain;
          req.userId = decoded.userId;
          req.authMethod = 'app_jwt';
          console.debug('[SessionToken] Verified app JWT for shop:', req.shopDomain);
          return next();
        }
        // Valid JWT but no shopDomain — fall through
        req.userId = decoded.userId;
        req.authMethod = 'app_jwt_no_shop';
      } catch (jwtErr) {
        console.warn('[SessionToken] All token verification failed:', err.message, jwtErr.message);
      }
    }
  }

  // No valid session token — proceed to next auth method (X-Shop-Domain header)
  next();
}

/**
 * Middleware to load shop data (access token etc.) from DB based on req.shopDomain.
 * Must run after verifySessionToken.
 */
export function loadShopData(req, res, next) {
  if (req.shopDomain && !req.shopData) {
    const shop = getShop(req.shopDomain);
    if (shop) {
      req.shopData = shop;
    }
  }
  next();
}

export default verifySessionToken;
